name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's latest code
      - name: Checkout the Repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ariaafsar
          outputs: dist/snake.svg

      # Upload the generated snake animation
      - name: Upload the Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg

      # Optionally, generate a GIF of the snake animation
      - name: Generate Snake GIF
        uses: Platane/snk/gif@v3
        with:
          github_user_name: ariaafsar
          outputs: dist/snake.gif
